### ISSUE TITLE
Add helm chart for easy deployment?

### ISSUE THREAD

**Issue by omerlh** [lunarway/snyk_exporter#6]
How can I publish this on kubernetes cluster? Is there a chart that I can use?

**Comment by kaspernissen** [comment]
There is a section in the README describing deployment to Kubernetes using the deployment.yaml and secret.yaml from the examples folder. Once you've added your Snyk API token as a base64 encoded secret, you can basically deploy it with `kubectl apply -f examples/`. Not seeing much value in adding support for helm, because you only have to add one single variable. But it would make sense to support the common package manager for Kubernetes, though, for people already using helm. Should be easy to do.

**Comment by omerlh** [comment]
Yep, the only reason to use helm is so I'll not have to write these files myself or copy them :)

**Comment by kaspernissen** [comment]
Since the one variable, the Snyk API token is a secret, how and where would you expect to add the variable? I'm not that familiar with helm, especially not with how to deal with secrets.

**Comment by omerlh** [comment]
Check out this [chart](https://github.com/Soluto/helm-charts/tree/master/charts/kamus), I had a similar issue and was able to solve it. 
For my use case, I'm going to do something a bit different. We're using [Kamus](https://github.com/soluto/kamus) to handle secrets, so I'm basically going to do a quick patch so I can pass a configuration file, extract the token from this file and run the exporter. Not ideal, but better than working with secrets. So actually, thinking about it, I might end up using my own files.

**Comment by Crevil** [comment]
I’m not familiar with Helm either. But I’m open for adding it if it makes sense and simplifies usage for some users. 

Could you provide a PR under the `examples` folder?

**Comment by omerlh** [comment]
Sure, I might do that at some point, but as I said - helm is not of a much value for us right now :)

**Comment by Crevil** [comment]
Ok. I’ll close this one then. Feel free to reopen in the future if this becomes relevant. 👍

**Comment by omerlh** [comment]
Cool, also good to keep it here for future users :)
